### ISSUE TITLE
error: read_image sampler_t is not a constant argument

### ISSUE THREAD

**Issue by steveneliuk** [KhronosGroupArchives/webcl-validator#59] opened 2013-12-12 22:37 UTC
Strange cause sampler is const,

```// copy image1 to image2 using image read function

__kernel void image_copy(__read_only image2d_t image1, __write_only image2d_t image2)
{

```
const int xout = get_global_id(0);
const int yout = get_global_id(1);
const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;
float4 pixel;

pixel = read_imagef(image1, sampler, (int2)(xout,yout));
write_imagef(image2, (int2)(xout,yout), pixel);
```

}```

**Comment by toaarnio** [comment] 2013-12-13 10:33
This is a duplicate of issue https://github.com/KhronosGroup/webcl-validator/issues/55.

**Closed as completed by toaarnio** 2013-12-13 10:33 UTC
Labels: duplicate
