### ISSUE TITLE
Failed to build program with validated kernel

### ISSUE THREAD

**Issue by wolfviking0** [KhronosGroupArchives/webcl-validator#67] opened 2013-12-17 23:02 UTC
Hi, I am working on the validator with the translator, and I start to do some test with my sample, one of them [Noise](https://developer.apple.com/librarY/mac/samplecode/OpenCL_Procedural_Noise_Example/Introduction/Intro.html) work well with the native kernel, when i call validator on it during the execution of the code I have an error when I build the program

Building compute program...
Error: Failed to build program executable!
<program source>:220:64: error: expected expression
__constant _WclConstants _wcl_constant_allocations = { (float4), 255, 256, {151,160,137,91,90,15,
                                                               ^
<program source>:263:13: error: expected expression
}, (float4) };
            ^
<program source>:450:5: warning: no previous prototype for function 'mod'
int mod(_WclProgramAllocations *_wcl_allocs, int x, int a)

I can share the generated code if it's necessary.

Tony

**Comment by elhigu** [comment] 2013-12-18 12:23
Hi, looks like those errors are caused by clang bug, which does not allow handling e.g.
(float4)(1,2,3,4) initializers correctly. When initializer is parsed, produced AST node does not contain initial values. You should be able to work around this by wrapping each vector literal initialization to parenthesis:

e.g. instead of

```
__constant float4 ZERO_F4 = (float4)(0.0f, 0.0f, 0.0f, 0.0f);
__constant float4 ONE_F4 = (float4)(1.0f, 1.0f, 1.0f, 1.0f);
```

write: 

```
__constant float4 ZERO_F4 = ((float4)(0.0f, 0.0f, 0.0f, 0.0f));
__constant float4 ONE_F4 = ((float4)(1.0f, 1.0f, 1.0f, 1.0f));
```

We hope that this works better after 3.4 update is ready. If not, we might need to add that style fix to one of the validators input normalization passes.

I tried fixing those and was able to produce and compile instrumented code.

**Comment by steveneliuk** [comment] 2013-12-19 17:50
Thank you Anthony for detailing the issue,

Vincit, could you please add this issue to the issues doc for the validator? Likewise, would make sense in incorporate into the normalization pass. However, if this is fixed in 3.4... we get it for free.

Lets not lose track of it though,

**Comment by elhigu** [comment] 2013-12-20 08:56
I think this github issue could just be just left open until the bug is fixed. We have already started the work on llvm 3.4 porting so it shouldn't take long to get resolution.

**Comment by elhigu** [comment] 2014-01-10 21:54
I tried running  3.4 based validator for  `__constant int4 test = (int4)(1,2,3,4);` initializer of generated code did look correct `__constant _WclConstants _wcl_constant_allocations = { (int4)(0,2,3,4) };`.

Next step will be to fix test cases to use unwrapped initializers...

**Closed as completed** 2014-02-07 17:27 UTC
